DjangoWebApp/DjangoWebApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='webapp')),
    path('admin/', admin.site.urls),
    path('webapp/', include("webapp.urls")),
]

DjangoWebApp/webapp/urls.py
from django.urls import path
from django.views.generic import RedirectView

from . import views

app_name = 'webapp'
urlpatterns = [
    path('', RedirectView.as_view(url="index")),
    path('index', views.IndexView.as_view(), name='index'),
    path('thanks', views.Thanks.as_view()),
    path('game', views.GameView.as_view()),
    path('scoreboard', views.ScoreboardView.as_view()),
]

DjangoWebApp/webapp/models.py
from django.db import models


class ScoreboardModel(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateTimeField()
    game_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name

DjangoWebApp/webapp/forms.py
from django import forms

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import ScoreboardModel


class GameForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(GameForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Nombre:'
        self.helper = FormHelper()
        self.helper.form_id = 'id-exampleForm'
        self.helper.form_class = 'blueForms'
        self.helper.form_method = 'post'
        self.helper.form_action = 'index'

        self.helper.add_input(
            Submit('submit', 'Jugar!', css_class="float-right")
        )

    class Meta:
        model = ScoreboardModel
        fields = [
            'name',
        ]

DjangoWebApp/webapp/views.py
import os
from datetime import datetime

from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.shortcuts import redirect

from .forms import GameForm
from .models import ScoreboardModel


class IndexView(CreateView):
    template_name = 'webapp/index.html'
    success_url = '/webapp/game'
    form_class = GameForm

    def get_context_data(self, **kwargs):
        hostname = os.uname().nodename
        context = super().get_context_data(**kwargs)
        context.update({
            'hostname': hostname,
        })
        return context

    def post(self, request, **kwargs):
        form = self.get_form()
        game = form.save(commit=False)
        game.date = datetime.now()
        game.save()
        return redirect(self.success_url)


class Thanks(TemplateView):
    template_name = 'webapp/thanks.html'


class ScoreboardView(ListView):
    template_name = 'webapp/scoreboard.html'
    model = ScoreboardModel


class GameView(TemplateView):
    template_name = 'webapp/game.html'

DjangoWebApp/webapp/templates/webapp/base.html
{% load static %}
<!DOCTYPE html>
<html class="h-100">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>{% block title %}Vacaciones en Las Toninas!{% endblock title %}</title>
        {% block css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="{% static 'webapp/css/base.css' %}" type="text/css">
        {% endblock css %}
        {% block js %}
        <script
          src="https://code.jquery.com/jquery-3.4.1.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
          crossorigin="anonymous"></script>
        <script
          src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
          crossorigin="anonymous"></script>
        {% endblock js %}
        {% endblock head %}
    </head>
    <body class="d-flex flex-column h-100">
        {% block body %}
        <header>
        {% block navbar %}
        <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
          <a class="navbar-brand" href="/">Toninas</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            {% block menu %}
              <li class="nav-item active">
                <a class="nav-link" href="/">Casucha<span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                  <a class="nav-link" href="scoreboard">Posiciones<span class="sr-only">(current)</span></a>
              </li>
            {% endblock menu %}
            </ul>
          </div>
        </nav>
        {% endblock navbar %}
        </header>
        {% block main %}
        <main class="flex-shrink-0">
            <div class="container">
                {% block maincontainer %}
                {% endblock maincontainer %}
            </div>
        </main>
        {% endblock main %}
        {% block footer %}
        <footer class="footer mt-auto py-3">
            <div class="container">
                <span>Vacaciones en las Toninas - SysArmy</span>
            </div>
        </footer>
        {% endblock footer %}
        {% endblock body %}
    </body>
</html>

DjangoWebApp/webapp/templates/webapp/game.html
{% extends "webapp/base.html" %}
{% load static crispy_forms_tags %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'webapp/css/game.css' %}" type="text/css">
{% endblock css %}

{% block js %}
{{ block.super }}
<script src="{% static 'webapp/js/game.js' %}"></script>
{% endblock js %}

{% block maincontainer %}
<div class="index-container">
    <h1 class="text-center">
        Recuperá el Datacenter!
    </h1>
</div>
{% endblock maincontainer %}

DjangoWebApp/webapp/templates/webapp/index.html
{% extends "webapp/base.html" %}
{% load static crispy_forms_tags %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'webapp/css/index.css' %}" type="text/css">
{% endblock css %}

{% block maincontainer %}
<div class="index-container">
    <h1 class="text-center">
        Aloha Terrícolas!
    </h1>
    <p>
        Bienvenidos a Las Toninas!
    </p>
    <p>
        Si esperaban encontrar una playa, pues se equivocaron...
    </p>
    <div class="formContainer jumbotron">
        <h3><b>Comenzar a jugar</b></h3>
        {% crispy form form.helper %}
    </div>
</div>
{% endblock maincontainer %}

DjangoWebApp/webapp/templates/webapp/scoreboard.html
{% extends "webapp/base.html" %}

{% block maincontainer %}
<div class="thanks-container">
    <h1 class="text-center">
        Como anduvo eso??? Acá están las posiciones...
    </h1>
    <div class="table-responsive-sm">
    <table class="table table-light table-striped table-hover">
        <thead class="thead-dark">
            <th>Nombre</th>
            <th>Tiempo</th>
            <th>Fecha de jugada</th>
        </thead>
        <tbody>
            {% for score in object_list %}
            <tr>
                <td>{{ score.name }}</td>
                <td>{{ score.experience }}</td>
            </tr> 
            {% endfor %}
        </tbody>
    </table>
    </div>
</div>
{% endblock maincontainer %}

DjangoWebApp/webapp/templates/webapp/thanks.html
{% extends "webapp/base.html" %}

{% block maincontainer %}
<div class="thanks-container col-12">
    <div class="col-12">
        <h1 class="text-center">
            Gracias campeón! <i class="fa fa-hand-rock-o" aria-hidden="true"></i>
        </h1>
    </div>
    <div class="col-12">
        <a class="btn btn-primary " href="{% url 'webapp:index' %}">Volver a casa</a>
    </div>
</div>
{% endblock maincontainer %}